In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df.head()

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
def initialize_parameters(layer_dims):
    ## making dictionary for initializing the values of weights and bias (w = 0.1 and b = 0)
    parameters = {}
    L = len(layer_dims) ## this length helps to iterate the loop
    for l in range(1 , L):
        ## very simple interpretation of finding weights and bias 
        
        parameters['W' + str(l)] = np.ones((layer_dims[l-1] , layer_dims[l])) * 0.1
        
        parameters['b' + str(l)] = np.zeros((layer_dims[l] , 1))

    return parameters

In [5]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [6]:
def linear_forward(A_prev, W, b):
  
  Z = np.dot(W.T, A_prev) + b
  
  return Z

In [7]:
# Forward Prop

def L_layer_forward(X, parameters):
    A = X
    for l in range(1,3):
        A_prev = A 
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
#         print("A"+str(l-1)+": ", A_prev)
#         print("W"+str(l)+": ", Wl)
#         print("b"+str(l)+": ", bl)
#         print("--"*20)

        A = linear_forward(A_prev, Wl, bl)
#         print("A"+str(l)+": ", A)
#         print("**"*20)
    return A,A_prev

In [8]:
X = df[['cgpa' , 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]
parameters = initialize_parameters([2,2,1])
y_hat , A1 = L_layer_forward(X, parameters)

In [9]:
y_hat = y_hat[0][0]

In [10]:
def update_parameters(parameters,y,y_hat,A1,X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
    parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))
    
    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [11]:
update_parameters(parameters,y,y_hat,A1,X)

In [12]:
parameters ## for first student

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [13]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729625
Epoch -  4 Loss -  3.252093863403161
Epoch -  5 Loss -  1.3407132589299964


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

In [14]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
  Using cached tensorflow-2.15.0-cp39-cp39-win_amd64.whl (2.1 kB)
     ------------------------------------ 300.8/300.8 MB 427.2 kB/s eta 0:00:00
     ------------------------------------ 938.4/938.4 kB 259.4 kB/s eta 0:00:00
     ------------------------------------ 442.0/442.0 kB 282.0 kB/s eta 0:00:00
     -------------------------------------- 65.5/65.5 kB 708.3 kB/s eta 0:00:00
     ---------------------------------------- 5.5/5.5 MB 614.4 kB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 1.1 MB/s eta 0:00:00
     -------------------------------------- 130.2/130.2 kB 1.1 MB/s eta 0:00:00
     -------------------------------------- 24.4/24.4 MB 688.6 kB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 778.6 kB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 656.0 kB/s eta 0:00:00
     -------------------------------------- 413.4/413.4 kB

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [69]:
## Tensor Flow implementation of Backpropagation 


import tensorflow
from tensorflow import keras 
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense

In [70]:
model = Sequential()

model.add(Dense(2 , activation = 'linear' , input_dim = 2))
model.add(Dense(1 , activation = 'linear'))

In [71]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 2)                 6         
                                                                 
 dense_7 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [72]:
## keras randomly assigns the weights 

model.get_weights()

[array([[ 0.8309468,  0.0783056],
        [ 1.0192655, -0.1881231]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.45405877],
        [-1.3485808 ]], dtype=float32),
 array([0.], dtype=float32)]

In [73]:
## but we have to assign the weights according to our implementation 

new_weights = [ np.array([[0.1 , 0.1] , 
                         [0.1 , 0.1]] , dtype = np.float32),
              np.array([0. , 0.] , dtype = np.float32) , 
              np.array([[0.1] , 
                       [0.1]] , dtype = np.float32), 
              np.array([0.] , dtype = np.float32)]

In [74]:
model.set_weights(new_weights)

In [75]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [76]:
## assigning the value of learning rate = 0.001

optimizer = keras.optimizers.Adam(learning_rate=0.001)

In [77]:
## compilation step 

model.compile(loss= 'mse' , optimizer = optimizer)

In [78]:
model.fit(df.iloc[:,:-1].values, df.iloc[:,-1].values , verbose = 1 , epochs = 70 , batch_size = 1)

Epoch 1/70
4/4 [==============================] - 1s 5ms/step - loss: 27.8873
Epoch 2/70
4/4 [==============================] - 0s 5ms/step - loss: 27.5830
Epoch 3/70
4/4 [==============================] - 0s 7ms/step - loss: 27.2296
Epoch 4/70
4/4 [==============================] - 0s 7ms/step - loss: 26.9070
Epoch 5/70
4/4 [==============================] - 0s 9ms/step - loss: 26.5653
Epoch 6/70
4/4 [==============================] - 0s 7ms/step - loss: 26.1874
Epoch 7/70
4/4 [==============================] - 0s 7ms/step - loss: 25.8133
Epoch 8/70
4/4 [==============================] - 0s 8ms/step - loss: 25.4408
Epoch 9/70
4/4 [==============================] - 0s 7ms/step - loss: 25.0780
Epoch 10/70
4/4 [==============================] - 0s 8ms/step - loss: 24.6410
Epoch 11/70
4/4 [==============================] - 0s 9ms/step - loss: 24.2445
Epoch 12/70
4/4 [==============================] - 0s 7ms/step - loss: 23.7892
Epoch 13/70
4/4 [==============================] - 0s 7ms/ste